### ISSUE TITLE
Not exporting the css file anymore?

### ISSUE THREAD

**Issue by digoburigo** [watergis/maplibre-gl-legend#10]
**Describe the bug**

**To Reproduce**
1. install the lib
2. try to import the css with `import "@watergis/maplibre-gl-legend/css/styles.css";` like before.
3. Dont find this file

**Expected behavior**
Same as the old version?

**Screenshots**
![image](https://github.com/watergis/maplibre-gl-legend/assets/28462822/2c0d82fc-c18b-4809-ac5c-1f4213555daa)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version latest

**Comment by JinIgarashi** [comment]
@digoburigo I am sorry for inconvenience. Because I changed from webpack to vite to build, folder structure was changed. try the following CSS path.

import '@watergis/maplibre-gl-legend/dist/maplibre-gl-legend.css';


For CDN, please also use the following new path.

<link
  href="https://www.unpkg.com/@watergis/maplibre-gl-legend@latest/dist/maplibre-gl-legend.css"
  rel="stylesheet"
/>
<script src="https://www.unpkg.com/@watergis/maplibre-gl-legend@latest/dist/maplibre-gl-legend.umd.js"></script>

**Comment by JinIgarashi** [comment]
Let me close this issue. Feel free to reopen if there is an issue of loading css

**Comment by digoburigo** [comment]
That was it. Thanks for the info!
